package com.wire.bots.polls.setup.logging

/**
 * ID retrieved from the header X-Request-Id coming from the infrastructure nginx.
 */
const val INFRA_REQUEST = "infra_request"

/**
 * ID generated by this application for particular request.
 */
const val APP_REQUEST = "app_request"

/**
 * ID of the user sending message.
 */
const val USER_ID = "user_id"
